# Generated by Django 5.2.1 on 2025-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('tipo_vehiculo', models.CharField(choices=[('Auto', 'Auto'), ('Moto', 'Moto'), ('Camioneta', 'Camioneta')], default='Auto', max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
            ],
        ),
    ]
