# Generated by Django 5.2.1 on 2025-06-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='Estado',
        ),
    ]
