# Generated by Django 5.2.1 on 2025-06-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0002_remove_vehiculo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('tipo_vehiculo', models.CharField(choices=[('Auto Electrico', 'Auto Electrico'), ('Moto Electrico', 'Moto Electrico'), ('Camioneta Electrica', 'Camioneta Electrica')], default='Auto Electrico', max_length=100)),
                ('Precio', models.CharField(max_length=100)),
            ],
        ),
    ]
