# Generated by Django 5.2.1 on 2025-06-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0003_vehiculoelec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='Precio',
            new_name='PrecioE',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='año',
            new_name='añoE',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='marca',
            new_name='marcaE',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='modelo',
            new_name='modeloE',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='tipo_vehiculo',
            new_name='tipo_vehiculoE',
        ),
    ]
