# Generated by Django 5.2.1 on 2025-06-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0004_rename_precio_vehiculoelec_precioe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='PrecioE',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='añoE',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='marcaE',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='modeloE',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='vehiculoelec',
            old_name='tipo_vehiculoE',
            new_name='tipo_vehiculo',
        ),
    ]
