# Generated by Django 5.2.1 on 2025-06-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0005_rename_precioe_vehiculoelec_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('tipo_vehiculo', models.CharField(choices=[('Auto Usado', 'Auto Usado'), ('Moto Usado', 'Moto Usado'), ('Camioneta Usada', 'Camioneta Usada')], default='Auto Usado', max_length=100)),
                ('Precio', models.CharField(max_length=100)),
            ],
        ),
    ]
