# Generated by Django 5.0.7 on 2025-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0006_vehiculousado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=100)),
                ('logo_marca', models.CharField(max_length=10)),
                ('informacion_marca', models.CharField(max_length=100)),
            ],
        ),
    ]
