# Generated by Django 5.0.7 on 2025-06-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0007_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='logo_marca',
        ),
    ]
