# Generated by Django 5.0.7 on 2025-06-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0009_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre_marca',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='Proyecto_Vehiculos.marca', to_field='nombre_marca'),
        ),
    ]
