# Generated by Django 5.0.7 on 2025-07-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0015_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoelec',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_electricos', to='Proyecto_Vehiculos.marca'),
        ),
        migrations.AlterField(
            model_name='vehiculousado',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_usados', to='Proyecto_Vehiculos.marca'),
        ),
    ]
