# Generated by Django 5.0.7 on 2025-07-12 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0017_comentariouso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Proyecto_Vehiculos.vehiculoelec')),
            ],
        ),
    ]
